# Generated by Django 4.1.3 on 2022-11-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_comments_listing_alter_user_id_bidding"),
    ]

    operations = [
        migrations.RenameModel(old_name="Comments", new_name="Comment",),
        migrations.AlterField(
            model_name="listing", name="title", field=models.TextField(),
        ),
    ]
