# Generated by Django 4.1.3 on 2022-11-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_rename_comments_comment_alter_listing_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing", name="title", field=models.CharField(max_length=64),
        ),
    ]
